
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/dev.env

networks:
  default:
    name: fullstack-network
